name       : xsel
version    : 1.2.0
release    : 1
source     :
    - git|https://github.com/kfish/xsel.git : 3254b787c5ea505585f182c32b7aeaf70767309f
license    : MIT
component  : xorg.apps
summary    : Manipulate the X selection
description: |
    Manipulate the X selection (X11 keyboard, etc.)
builddeps  :
    - pkgconfig(x11)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
